FROM python:3.12-slim
WORKDIR /app
COPY common/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY common/metrics.py .
COPY product/app.py .
EXPOSE 8002
CMD ["gunicorn", "-b", "0.0.0.0:8002", "app:app", "--workers", "2"]
